openapi: '3.0.2'
info:
  title: Succulent WebHook
  version: 'v1'
paths:
  '/succulent-content':
    post:
      operationId: succulentContentCreated
      requestBody:
        content:
          'application/json':
            schema:
              $ref: '#/components/schemas/SucculentContentAdded'
        required: true
      responses:
        '200':
          description: Succulent content added
          content:
            'application/json':
              schema:
                type: object
                properties:
                  statusCode:
                    type: string
      x-amazon-apigateway-request-validator: basic
      x-amazon-apigateway-integration:
        type: aws
        uri: {Fn::Sub: 'arn:aws:apigateway:${AWS::Region}:sqs:path//${AWS::AccountId}/${self:custom.queue_name}'}
        httpMethod: post
        credentials: {Fn::GetAtt: [ApiGatewaySqsIam, Arn]}
        requestParameters: {'integration.request.header.Content-Type': "'application/x-www-form-urlencoded'"}
        requestTemplates:
          'application/json':
            'Action=SendMessage&MessageBody=$util.urlEncode($input.json("$"))'
        passthroughBehavior: when_no_templates
        responses:
          default:
            statusCode: "200"
            responseTemplates:
              'application/json': '{"statusCode": "200"}'
components:
  schemas:
    SucculentContentAdded:
      type: object
      properties:
        row:
          type: string
        timestamp:
          type: string
        title:
          type: string
        body:
          type: string
        imageUrl:
          type: string
          format: url
x-amazon-apigateway-request-validators:
  basic:
    validateRequestParameters: false
    validateRequestBody: true