service: succulent-of-the-day
custom:
  bucketName: succulent-of-the-day-8cffev5njytoen
package:
  individually: true
  excludeDevDependencies: true
provider:
  name: aws
  runtime: nodejs8.10
  memorySize: 256
  versionFunctions: false
  stage: ${opt:stage, 'dev'}
  variableSyntax: "\\${((?!AWS)[ ~:a-zA-Z0-9._'\",\\-\\/\\(\\)]+?)}"
  environment:
    S3_BUCKET_NAME: ${self:custom.bucketName}
  iamRoleStatements:
    - Effect: 'Allow'
      Action:
        - s3:GetObject
        - s3:ListBucket
      Resource: 'arn:aws:s3:::${self:custom.bucketName}/*'
functions:
  handler:
    handler: custom/index.handler
    package:
      path: custom
      include:
        - custom/index.js
        - custom/lib/**/*.js
      exclude:
        - custom/**/*.test.js
    events:
      - s3:
          bucket: ${self:custom.bucketName}
          rules:
            - prefix: uploads/
            - suffix: .jpg
